document.write(''
    + '<ul class="nav"> '
    + '  <li class="nav-item nav-profile border-bottom"> '
    + '    <a href="http://www.irotrujillo.gob.pe/" target="_blank" class="nav-link flex-column"> '
    + '      <div class="nav-profile-image"> '
    + '        <img src="../Estilos/Imagenes/Logo.png" alt="image" class="profile-pic"> '
    + '      </div> '
    + '    </a> '
    + '  </li> '
    + '  <li class="pt-2 pb-1"> '
    + '    <span class="nav-item-head">SIPA Web</span> '
    + '  </li> '
    //+ '  <li class="nav-item"> '
    //+ '    <a class="nav-link" data-bs-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic"> '
    //+ '      <i class="mdi mdi-crosshairs-gps menu-icon"></i> '
    //+ '      <span class="menu-title">UI Elements</span> '
    //+ '      <i class="menu-arrow"></i> '
    //+ '    </a> '
    //+ '    <div class="collapse" id="ui-basic"> '
    //+ '      <ul class="nav flex-column sub-menu"> '
    //+ '        <li class="nav-item"> <a class="nav-link" href="../../pages/ui-features/buttons.html">Buttons</a></li> '
    //+ '        <li class="nav-item"> <a class="nav-link" href="../../pages/ui-features/dropdowns.html">Dropdowns</a></li> '
    //+ '        <li class="nav-item"> <a class="nav-link" href="../../pages/ui-features/typography.html">Typography</a></li> '
    //+ '      </ul> '
    //+ '    </div> '
    //+ '  </li> '

    //+ '  <li class="nav-item"> '
    //+ '    <a class="nav-link" data-bs-toggle="collapse" href="#forms" aria-expanded="false" aria-controls="forms"> '
    //+ '      <i class="mdi mdi-format-list-bulleted menu-icon"></i> '
    //+ '      <span class="menu-title">Forms</span> '
    //+ '      <i class="menu-arrow"></i> '
    //+ '    </a> '
    //+ '    <div class="collapse" id="forms"> '
    //+ '      <ul class="nav flex-column sub-menu"> '
    //+ '        <li class="nav-item"> <a class="nav-link" href="../../pages/forms/basic_elements.html">Form Elements</a></li> '
    //+ '      </ul> '
    //+ '    </div> '
    //+ '  </li> '

    + '  <li class="nav-item" id="mEstad"> '
    + '    <a class="nav-link" data-bs-toggle="collapse" href="#mEstS" aria-expanded="false" aria-controls="mEstS"> '
    + '      <i class="fa fa-id-card-o menu-icon"></i> '
    + '      <span class="menu-title">Estadistica</span> '
    + '      <i class="menu-arrow"></i> '
    + '    </a> '
    + '    <div class="collapse" id="mEstS"> '
    + '      <ul class="nav flex-column sub-menu"> '
    + '        <li class="nav-item"> <a class="nav-link" href="../Estadistica/HCRegistro.aspx" id="mEstSRegHC">Registro HC</a></li> '
    + '        <li class="nav-item"> <a class="nav-link" href="../Estadistica/HCRegistro3.aspx" id="mEstSConHC">Consulta</a></li> '
    + '        <li class="nav-item"> <a class="nav-link" href="#" id="mEstSEdiHC">Edicion</a></li> '
    + '        <li class="nav-item"> <a class="nav-link" href="#" id="mEstSAnuHC">Anulación</a></li> '
    + '      </ul> '
    + '    </div> '
    + '  </li> '

    + '  <li class="nav-item" id="mEnfer"> '
    + '    <a class="nav-link" data-bs-toggle="collapse" href="#mEnfS" aria-expanded="false" aria-controls="mEnfS"> '
    + '      <i class="fa fa-medkit menu-icon"></i> '
    + '      <span class="menu-title">Enfermeria</span> '
    + '      <i class="menu-arrow"></i> '
    + '    </a> '
    + '    <div class="collapse" id="mEnfS"> '
    + '      <ul class="nav flex-column sub-menu"> '
    + '        <li class="nav-item"> <a class="nav-link" href="#" id="mEnfSRegHC">Registro</a></li> '
    + '        <li class="nav-item"> <a class="nav-link" href="#" id="mEnfSConHC">Consulta</a></li> '
    + '        <li class="nav-item"> <a class="nav-link" href="#" id="mEnfSEdiHC">Edicion</a></li> '
    + '        <li class="nav-item"> <a class="nav-link" href="#" id="mEnfSAnuHC">Anulacion</a></li> '
    + '      </ul> '
    + '    </div> '
    + '  </li> '

    + '  <li class="nav-item" id="mSIS"> '
    + '    <a class="nav-link" data-bs-toggle="collapse" href="#mSisS" aria-expanded="false" aria-controls="mSisS"> '
    + '      <i class="fa fa-strikethrough menu-icon"></i> '
    + '      <span class="menu-title">SIS</span> '
    + '      <i class="menu-arrow"></i> '
    + '    </a> '
    + '    <div class="collapse" id="mSisS"> '
    + '      <ul class="nav flex-column sub-menu"> '

    + '      </ul> '
    + '    </div> '
    + '  </li> '

    + '  <li class="nav-item" id="mConsul"> '
    + '    <a class="nav-link" data-bs-toggle="collapse" href="#mConS" aria-expanded="false" aria-controls="mConS"> '
    + '      <i class="fa fa-user-md menu-icon"></i> '
    + '      <span class="menu-title">Consultorio</span> '
    + '      <i class="menu-arrow"></i> '
    + '    </a> '
    + '    <div class="collapse" id="mConS"> '
    + '      <ul class="nav flex-column sub-menu"> '
    + '        <li class="nav-item"> <a class="nav-link" href="../Consultorio/ConsRegistro.aspx" >Registro Consulta</a></li> '

    + '      </ul> '
    + '    </div> '
    + '  </li> '

    + '  <li class="nav-item" id="mSOP"> '
    + '    <a class="nav-link" data-bs-toggle="collapse" href="#mSopS" aria-expanded="false" aria-controls="mSopS"> '
    + '      <i class="fa fa-plus-square menu-icon"></i> '
    + '      <span class="menu-title">Sala de Operaciones</span> '
    + '      <i class="menu-arrow"></i> '
    + '    </a> '
    + '    <div class="collapse" id="mSopS"> '
    + '      <ul class="nav flex-column sub-menu"> '
    + '        <li class="nav-item"> <a class="nav-link" href="../SOP/SOPNuePac.aspx" >Nuevos Pacientes </a></li> '
    + '        <li class="nav-item"> <a class="nav-link" href="../SOP/SOPHistPac.aspx" >Historial Pacientes </a></li> '
    + '        <li class="nav-item"> <a class="nav-link" href="../SOP/SOPErrRefra.aspx" >Errores Refractivos </a></li> '
    + '        <li class="nav-item"> <a class="nav-link" href="../SOP/SOPManten.aspx" >Mantenedores </a></li> '

    + '      </ul> '
    + '    </div> '
    + '  </li> '

    + '  <li class="nav-item" id="mSSSS"> '
    + '    <a class="nav-link" data-bs-toggle="collapse" href="#mSsS" aria-expanded="false" aria-controls="mSsS"> '
    + '      <i class="fa fa-users menu-icon"></i> '
    + '      <span class="menu-title">Servicio Social</span> '
    + '      <i class="menu-arrow"></i> '
    + '    </a> '
    + '    <div class="collapse" id="mSsS"> '
    + '      <ul class="nav flex-column sub-menu"> '

    + '      </ul> '
    + '    </div> '
    + '  </li> '

    + '  <li class="nav-item" id="mUtil"> '
    + '    <a class="nav-link" data-bs-toggle="collapse" href="#mUtilS" aria-expanded="false" aria-controls="mUtilS"> '
    + '      <i class="fa fa-wrench menu-icon"></i> '
    + '      <span class="menu-title">Utilitarios</span> '
    + '      <i class="menu-arrow"></i> '
    + '    </a> '
    + '    <div class="collapse" id="mUtilS"> '
    + '      <ul class="nav flex-column sub-menu"> '

    + '      </ul> '
    + '    </div> '
    + '  </li> '


    + '  <li class="nav-item"> '
    + '  <hr> '
    + '    <a class="nav-link" href="../SesionA" > '
    + '      <i class="fa fa-unlock-alt menu-icon"></i> '
    + '      <span class="menu-title">Salir</span> '
    + '    </a> '
    + '  </li> '

    + '</ul> '
	
	+ '');
