document.write(''
    + '<div class="navbar-menu-wrapper d-flex align-items-stretch"> '
    + '  <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize"> '
    + '    <span class="mdi mdi-chevron-double-left"></span> '
    + '  </button> '
    + '  <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center"> '
    + '    <a class="navbar-brand brand-logo-mini" href="../../index.html"> '
    + '        <img src="../Estilos/Imagenes/favicon.png" alt="logo" /> '
    + '    </a> '
    + '  </div> '
    + '    <div id="menuHCRUD" > '
    + '      <ul class="navbar-nav"> '
    + '     <li id="LiMHGuardar" title="Agregar Nuevo Registro" onclick="fnGuardar()" style="background-color:white" > '
    + '		    <button class="btn btn-inverse-primary btn-icon"> '
    + '			    <i class="ti-save"></i> <br /> Añade '
    + '		    </button> '
    + '	    </li> '
    + '          <li id="" title="" onclick="" style="" >&nbsp </li> '
    + '     <li id="LiMHConsultar" title="Consultar Registros" onclick="fnConsultar()" style="background-color:white" > '
    + '		    <button class="btn btn-inverse-info btn-icon"> '
    + '			    <i class="ti-view-list-alt"></i> <br /> Busca '
    + '		    </button> '
    + '	    </li> '
    + '          <li id="" title="" onclick="" style="" >&nbsp </li> '
    + '     <li id="LiMHEditar" title="Editar un Registro" onclick="fnEditar()" style="background-color:white" > '
    + '		    <button class="btn btn-inverse-success btn-icon"> '
    + '			    <i class="ti-pencil-alt"></i> <br /> Edita '
    + '		    </button> '
    + '	    </li> '
    + '     '
    + '          <li id="" title="" onclick="" style="" >&nbsp&nbsp&nbsp </li> '
    + '     '
    + '     <li id="LiMHAnular" title="Eliminar un Registro" onclick="fnAnular()" style="background-color:white" > '
    + '		    <button class="btn btn-inverse-danger btn-icon"> '
    + '			    <i class="ti-close"></i> <br /> Borra '
    + '		    </button> '
    + '	    </li> '

    + '          <li id="" title="" onclick="" style="" >&nbsp&nbsp&nbsp </li> '
    + '     <li id="LiMHImprimir" title="Imprimir" onclick="fnImprimir()" style="background-color:white" > '
    + '		    <button class="btn btn-outline-secondary btn-icon"> '
    + '			    <i class="fa fa-print"></i> <br />  '
    + '		    </button> '
    + '	    </li> '
    + '      </ul> '
    + '    </div> '
    + '  <ul class="navbar-nav navbar-nav-right"> '
    + '    <li class="nav-item nav-profile dropdown d-none d-md-block"> '
    + '      <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-bs-toggle="dropdown" aria-expanded="false"> '
    + '        <div class="nav-profile-text">Sesion &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp </div> '
    + '      </a> '
    + '      <div class="dropdown-menu center navbar-dropdown" aria-labelledby="profileDropdown"> '
    + '        <a class="dropdown-item" href="#"> '
    + '          <i class="flag-icon flag-icon-bl me-3"></i> Perfil </a> '
    + '        <div class="dropdown-divider"></div> '
    + '        <a class="dropdown-item" href="#"> '
    + '          <i class="flag-icon flag-icon-cn me-3"></i> Configuracion </a> '
    + '        <div class="dropdown-divider"></div> '
    + '        <a class="dropdown-item" href="#"> '
    + '          <i class="flag-icon flag-icon-de me-3"></i> Cambiar Contraseña </a> '
    + '        <div class="dropdown-divider"></div> '
    + '        <a class="dropdown-item" href="../SesionA"> '
    + '          <i class="flag-icon flag-icon-ru me-3"></i> Cerrar Sesion </a> '
    + '      </div> '
    + '    </li> '
    + '    <li class="nav-item nav-logout d-none d-lg-block"><i class="mdi mdi-home-circle"></i></li> '
    + '  </ul> '
    + '  <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas"> '
    + '    <span class="mdi mdi-menu"></span> '
    + '  </button> '
    + '</div> '

    + '');
